//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRentalRecord
    {
        public int id { get; set; }
        public string customer_name { get; set; }
        public Nullable<System.DateTime> date_rental { get; set; }
        public Nullable<System.DateTime> date_return { get; set; }
        public Nullable<decimal> car_rental_cost { get; set; }
        public int car_type_id { get; set; }
    
        public virtual TypeofCar TypeofCar { get; set; }
    }
}
